# Generated by Django 5.2.3 on 2025-06-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_survey_age_group_alter_survey_barrier_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
