# Generated by Django 5.2.3 on 2025-06-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_25', '18-25'), ('26_35', '26-35'), ('36_50', '36-50'), ('50_plus', '50+')], max_length=20)),
                ('discovery_source', models.CharField(blank=True, max_length=100)),
                ('discovery_other', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('location_other', models.CharField(blank=True, max_length=255)),
                ('app_usage', models.BooleanField(default=False)),
                ('apps_used', models.JSONField(blank=True, default=list)),
                ('app_other', models.CharField(blank=True, max_length=255)),
                ('feature_preferences', models.JSONField(blank=True, default=dict)),
                ('motivation', models.IntegerField()),
                ('willingness', models.TextField(blank=True)),
                ('barriers', models.TextField(blank=True)),
                ('barrier_other', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
