# Generated by Django 5.2.3 on 2025-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='age_group',
            field=models.CharField(blank=True, choices=[('<18', 'Under 18'), ('18-24', '18 to 24'), ('24-34', '24 to 34'), ('35-44', '35 to 44'), ('45-54', '45 to 54'), ('55+', '55 and above')], max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='barrier_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='barriers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='motivation',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='survey',
            name='willingness',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
