[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10